Repository 13x54n/sunya, pull requests merged in 2024-06, with the labels that each got.

#1 🛸 feat: setup cairo and vite
  .eslintrc.cjs
  .gitignore
  README.md
  Scarb.lock
  Scarb.toml
  bun.lockb
  index.html
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/lib.cairo
  src/main.jsx
  vite.config.js
Labels: documentation, enhancement

#5 👛 ArgentX Mobile Wallet Connection
  Scarb.toml
  bun.lockb
  index.html
  package.json
  postcss.config.js
  public/1.jpg
  public/ecological-strategy-development-natural-resources-access-ecologists-cartoon-characters-eco-shield-environmental-protection-world-rescue_335657-3421.jpg
  public/hacker-activity-concept_23-2148542914.jpg
  public/logo.png
  public/vite.svg
  src/App.css
  src/App.jsx
  src/Router.jsx
  src/assets/react.svg
  src/components/L2WalletConnectKit.jsx
  src/components/Navbar.jsx
  src/contracts/ethereum/DIDRegistry.sol
  src/contracts/starknet/DIDRegistry.cairo
  src/index.css
  src/main.jsx
  src/mocks/RecentAudits.json
  src/pages/Audits.jsx
  src/pages/Documentation.jsx
  src/pages/GasTank.jsx
  src/pages/Home.jsx
  tailwind.config.js
Labels: documentation, enhancement

#7 ✨ fix: Update issue templates.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#6 📜 feat: Create LICENSE
  LICENSE
Labels: documentation, enhancement

#9 📜 documentation: project overview, installation
  README.md
  bun.lockb
  package.json
  scripts/install.bat
  scripts/install.sh
  src/Router.jsx
  src/components/Navbar.jsx
  src/pages/Audits.jsx
  src/pages/ContractVerification.jsx
  src/pages/Dashboard.jsx
  src/pages/DeploymentWizard.jsx
  src/pages/GasTank.jsx
  src/pages/Home.jsx
  src/pages/SecurityAnalysis.jsx
Labels: documentation, enhancement

#8 ⛽ page: dashboard layout completed
  bun.lockb
  package.json
  src/Router.jsx
  src/components/Navbar.jsx
  src/pages/Audits.jsx
  src/pages/ContractVerification.jsx
  src/pages/Dashboard.jsx
  src/pages/DeploymentWizard.jsx
  src/pages/GasTank.jsx
  src/pages/Home.jsx
  src/pages/SecurityAnalysis.jsx
Labels: documentation, enhancement

#10 🐛 package: static analysis dictionary created
  .gitignore
  Scarb.lock
  Scarb.toml
  packages/detectors/controlled_library_call.cairo
  packages/detectors/dead_code.cairo
  packages/detectors/unused_arguments.cairo
  packages/detectors/unused_events.cairo
  packages/detectors/unused_return.cairo
  packages/detectors/use_after_pop_front.cairo
  scripts/install.sh
  server/index.js
  server/package.json
  server/scripts/Detector.sh
  server/temp-audit-storage/README.md
  server/yarn.lock
  src/lib.cairo
  src/pages/Dashboard.jsx
  src/pages/SecurityAnalysis.jsx
Labels: documentation, enhancement, help wanted

#12 💽 log: tailed smart contract audit log into frontend after analysis
  bun.lockb
  package.json
  server/bun.lockb
  server/index.js
  server/package.json
  server/scripts/detector.sh
  server/scripts/install.sh
  server/temp-audit-storage/README.md
  server/temp-audit-storage/package-lock.json
  server/temp-audit-storage/package.json
  src/index.css
  src/pages/Dashboard.jsx
  src/pages/SecurityAnalysis.jsx
Labels: documentation

#16 🍎 doc: audit report as pdf and downlaod is enabled too.
  .eslintrc.cjs
  bun.lockb
  package.json
  server/index.js
  server/scripts/detector.sh
  src/pages/SecurityAnalysis.jsx
Labels: enhancement

#17 🧭 feat: Model Preparation for Vulnerabilities check
  packages/ExamplesVulnerableContracts/badContract.cairo
  packages/ExamplesVulnerableContracts/goodContract.cairo
  packages/SNCVulDetector/src/cairo_lexer.py
  packages/SNCVulDetector/src/data_preparation.py
  packages/SNCVulDetector/src/debug_inference.py
  packages/SNCVulDetector/src/inference.py
  packages/SNCVulDetector/src/main.py
  packages/SNCVulDetector/src/model_training.py
  packages/SNCVulDetector/src/tokenization.py
  packages/SNCVulDetector/src/utils.py
Labels: enhancement

#20 DID Completed for L2 -> Rapid for L1
  bun.lockb
  package.json
  src/lib.cairo
  src/pages/Documentation.jsx
Labels: documentation

#21 💀 fix: fixed SNCVulDetector path issue -> {linux, unix}
  Scarb.toml
  bun.lockb
  package.json
  packages/SNCVulDetector/src/debug_inference.py
  packages/SNCVulDetector/src/model_training.py
  src/AuditRegistry.sol
  src/lib.cairo
Labels: enhancement

#22 👻 fix: detector was unable to get VulDetector Model for prediction
  packages/SNCVulDetector/README.md
  server/scripts/detector.sh
  server/scripts/packages/ExamplesVulnerableContracts/badContract.cairo
  server/scripts/packages/ExamplesVulnerableContracts/goodContract.cairo
  server/scripts/packages/SNCVulDetector/.gitignore
  server/scripts/packages/SNCVulDetector/README.md
  server/scripts/packages/SNCVulDetector/src/cairo_lexer.py
  server/scripts/packages/SNCVulDetector/src/data_preparation.py
  server/scripts/packages/SNCVulDetector/src/debug_inference.py
  server/scripts/packages/SNCVulDetector/src/inference.py
  server/scripts/packages/SNCVulDetector/src/main.py
  server/scripts/packages/SNCVulDetector/src/model_training.py
  server/scripts/packages/SNCVulDetector/src/tokenization.py
  server/scripts/packages/SNCVulDetector/src/utils.py
  server/scripts/packages/detectors/controlled_library_call.cairo
  server/scripts/packages/detectors/dead_code.cairo
  server/scripts/packages/detectors/unused_arguments.cairo
  server/scripts/packages/detectors/unused_events.cairo
  server/scripts/packages/detectors/unused_return.cairo
  server/scripts/packages/detectors/use_after_pop_front.cairo
Labels: good first issue

#25 Wrapping up the project.
  bun.lockb
  package.json
  server/scripts/README.md
  server/scripts/packages/herodotus/.env
  server/scripts/packages/herodotus/herodotus.js
  server/scripts/packages/herodotus/package-lock.json
  server/scripts/packages/herodotus/package.json
  src/App.jsx
  src/AuditRegistry.sol
  src/components/3d-card.jsx
  src/components/MintAuditDidCard.jsx
  src/components/MintAuditDidDialogueModal.jsx
  src/components/Navbar.jsx
  src/components/SecurityAnalysisLoader.jsx
  src/components/multi-step-loader.jsx
  src/contracts/ethereum/DIDRegistry.sol
  src/contracts/starknet/DIDRegistry.cairo
  src/lib.cairo
  src/main.jsx
  src/mocks/RecentAudits.json
  src/pages/Audits.jsx
  src/pages/Dashboard.jsx
  src/pages/GasTank.jsx
  src/pages/SecurityAnalysis.jsx
  src/utils/SNABI.json
  src/utils/sunya_MapContract.contract_class.json
  vecel.json
  wallet.json
Labels: documentation, enhancement
